buy:
  #Turn on/off buying system (buy, addbuyitem, delbuyitem, adddiscount, deldiscount commands)
  active: true

sell:
  #Turn on/off selling system (sell, addsellitem, delsellitem commands)
  active: true

auction:
  #Turn on/off auction system (auc, bet commands)
  active: true
  #Auction duration in milliseconds
  duration: 300000
  #Periodicity of notifications about the ongoing auction (in milliseconds)
  notify-period: 60000
  #Price for starting an auction. Set 0 to turn it off
  start-tax: 0
  #End tax in percents (tax is taken from the final bid). Set 0 to turn it off
  end-tax: 0
  #Default compensation for loosing the lot. It's paid to a trader if the auction winner has no free space in his inventory to get the lot, and the trader have no free space to get it back. Set 0 to turn it off
  default-compensation: 0

general:
  #Plugin language. if <default> - server language will be used. If there is no translation in your language, there will be created a file called <your_lang>.lng with all strings in English. You'll have to translate them.
  language: default
  #Primary color of messages
  primary-color: a
  #Secondary color of messages
  secondary-color: 2
  #Color of error messages
  error-color: c
  #Saving info about all transactions to log
  transaction-logging: false
  #If true, a file with all strings will be created. You can edit the strings.
  save-translation: false