name: Trading Commands
main: ua.leonidius.trading.Main
version: 1.0.2
author: Leonidius20
api: ["1.0.0"]
description: Shop and auction system, based on commands.
depend:
- EconomyAPI
permissions:
  trading.editshoplist:
    description: Editing shop lists
    default: op